### ISSUE TITLE
instructions for running tests causing problems

### ISSUE THREAD

**Issue by d-d-d-dalia** [learn-co-curriculum/js-dom-and-events-konami-code-lab#1] opened 2018-03-17 17:05 UTC
index.html instructs:  

when mocha.run() is run, the tests will not pass regardless of the code being correct, however, running 'learn' passes them.

**Comment by maxwellbenton** [comment] 2018-04-06 19:52
Hi there @d-d-d-dalia ,

I'm having difficulty reproducing the issue reported.  Switching this lesson to the solution branch and testing both `mocha.run()` and `learn` will produce passing tests for both.  You can also 'fake' pass either of the two tests and both will behave the same in learn (i.g. if you add an event listener to the init() function that increments a value at every keypress, and then fires an alert when 10 keys are pressed, the first test will pass).  The second test will automatically pass initially because it is testing to see if an alert doesn't fire, which it won't without any code to call it.

I'm going to close this for now, but if you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙

**Closed by maxwellbenton** 2018-04-06 19:52 UTC
Labels: Product
